require 'rubygems'
require 'rake'
require 'echoe'

Echoe.new('dirclass', '0.0.2') do |p|
  p.description    = "A gem that extends the Dir class with a list method"
  p.url            = "http://github.com/johnvpetersen/dirclass_gem"
  p.author         = "John V. Petersen"
  p.email          = "johnvpetersen @nospam@ gmail.com"
  p.ignore_pattern = ["tmp/*", "script/*"]
  p.development_dependencies = []
end
